<?php
namespace Bitrix24\Presets;

class Uri
{
	const REQUEST_PARAM_DOMAIN = 'DOMAIN';
	const REQUEST_PARAM_PROTOCOL = 'PROTOCOL';
	const REQUEST_PARAM_LANG = 'LANG';
	const REQUEST_PARAM_AUTH_EXPIRES = 'AUTH_EXPIRES';
	const REQUEST_PARAM_MEMBER_ID = 'member_id';
	const REQUEST_PARAM_AUTH_ID = 'AUTH_ID';
	const REQUEST_PARAM_REFRESH_ID = 'REFRESH_ID';
}