<?php

declare(strict_types=1);

namespace Bitrix24\SDK\Services\Telephony\Common;

interface StatusSipCodeInterface
{
    //Provisional Responses
    const STATUS_TRYING = 100;
    const STATUS_RINGING = 180;
    const STATUS_CALL_IS_BEING_FORWARDED = 181;
    const STATUS_QUEUED = 182;
    const STATUS_SESSION_PROGRESS = 183;
    const STATUS_EARLY_DIALOG_TERMINATED = 199;
    //Successful Responses
    const STATUS_OK = 200;
    const STATUS_ACCEPTED = 202;
    const STATUS_NO_NOTIFICATION = 204;
    //Redirection Responses
    const STATUS_MULTIPIE_CHOICES = 300;
    const STATUS_MOVED_PERMANENTLY = 301;
    const STATUS_MOVED_TEMPORARILY = 302;
    const STATUS_USE_PROXY = 305;
    const STATUS_ALTERNATIVE_SERVICE=380;
    //Client Failure Responses
    const STATUS_BAD_REQUEST = 400;
    const STATUS_UNAUTHORIZED = 401;
    const STATUS_PAYMENT_REQUIRED = 402;
    const STATUS_FORBIDDEN = 403;
    const STATUS_NOT_FOUND = 404;
    const STATUS_METHOD_NOT_ALLOWED = 405;
    const STATUS_NOT_ACCEPTABLE = 406;
    const STATUS_PROXY_AUTHENTICATION_REQUIRED = 407;
    const STATUS_REQUEST_TIMEOUT = 408;
    const STATUS_C0NFLICT = 409;
    const STATUS_GONE = 410;
    const STATUS_LENGTH_REQUIRED = 411;
    const STATUS_CONDITIONAL_REQUEST_FAILED = 412;
    const STATUS_REQUEST_ENTITY_TOO_LARGE = 413;
    const STATUS_REQUEST_URI_TOO_LONG = 414;
    const STATUS_UNSUPPORTED_MEDIA_TYPE = 415;
    const STATUS_UNSUPPORTED_URI_SCHEME = 416;
    const STATUS_UNKNOWN_RESOURCE_PRIORITY = 417;
    const STATUS_BAD_EXTENSION = 420;
    const STATUS_EXTENSION_REQUIRED =421;
    const STATUS_SESSION_INTERVAL_TOO_SMALL = 422;
    const STATUS_INTERVAL_TOO_BRIED = 423;
    const STATUS_BAD_LOCATION_INFORMATION = 424;
    const STATUS_BAD_ALERT_MESSAGE = 425;
    const STATUS_USE_IDENTITY_HEADER = 428;
    const STATUS_PROVIDE_REFERRER_IDENTITY = 429;
    const STATUS_FLOW_FAILED = 430;
    const STATUS_ANONYMITY_DISALLOWED = 433;
    const STATUS_BAD_IDENTITY_INFO = 436;
    const STATUS_UNSUPPORTED_CERTIFICATE = 437;
    const STATUS_INVALID_IDENTITY_HEADER = 438;
    const STATUS_FIRST_HOP_LACKS_OUTBOUND_SUPPORT = 439;
    const STATUS_MAX_BREADTH_EXCEEDED = 440;
    const STATUS_BAD_INFO_PACKAGE = 469;
    const STATUS_CONSENT_NEEDED = 470;
    const STATUS_TEMPORARILY_UNAVAILABLE = 480;
    const STATUS_CALL_OR_TRANSACTION_DOES_NOT_EXIST = 481;
    const STATUS_LOOP_DETECTED = 482;
    const STATUS_TOO_MANY_HOPS = 483;
    const STATUS_ADDRESS_INCOMPLETE = 484;
    const STATUS_AMBIGUOUS = 485;
    const STATUS_BUSY_HERE = 486;
    const STATUS_REQUEST_TERMINATED = 487;
    const STATUS_NOT_ACCEPTABLE_HERE  = 488;
    const STATUS_BAD_EVENT = 489;
    const STATUS_REQUEST_PENDING = 491;
    const STATUS_UNDECIPHERABLE = 493;
    const STATUS_SECURITY_AGREEMENT_REQUIRED = 494;
    //Server Failure Responses
    const STATUS_INTERNAL_SERVER_ERROR = 500;
    const STATUS_NOT_IMPLEMENTED = 501;
    const STATUS_BAD_GATEWAY = 502;
    const STATUS_SERVICE_UNAVAILABLE = 503;
    const STATUS_SERVER_TIME_OUT = 504;
    const STATUS_VERSION_NOT_SUPPORTED = 505;
    const STATUS_MESSAGE_TOO_LARGE = 513;
    const STATUS_PUSH_NOTIFICATION_SERVICE_NOT_SUPPORTED = 555;
    const STATUS_PRECONDITION_FAILURE = 580;
    //Global Failure Responses
    const STATUS_BUSY_EVERYWHERE = 600;
    const STATUS_DECLINE = 603;
    const STATUS_DOES_NOT_EXIST_ANYWHERE = 604;
    const STATUS_GLOBAL_NOT_ACCEPTABLE = 606;
    const STATUS_UNWANTED = 607;
    const STATUS_REJECTED = 608;


}