<?php
namespace Bitrix24\Presets\CRM\Lead\UserField;

class Fields
{
	const EDIT_FORM_LABEL = 'EDIT_FORM_LABEL';
	const EDIT_IN_LIST = 'EDIT_IN_LIST';
	const ENTITY_ID = 'ENTITY_ID';
	const ERROR_MESSAGE = 'ERROR_MESSAGE';
	const FIELD_NAME = 'FIELD_NAME';
	const HELP_MESSAGE = 'HELP_MESSAGE';
	const ID = 'ID';
	const IS_SEARCHABLE = 'IS_SEARCHABLE';
	const LIST_ITEMS = 'LIST';
	const LIST_COLUMN_LABEL = 'LIST_COLUMN_LABEL';
	const LIST_FILTER_LABEL = 'LIST_FILTER_LABEL';
	const MANDATORY = 'MANDATORY';
	const MULTIPLE = 'MULTIPLE';
	const SETTINGS = 'SETTINGS';
	const SHOW_FILTER = 'SHOW_FILTER';
	const SHOW_IN_LIST = 'SHOW_IN_LIST';
	const SORT = 'SORT';
	const USER_TYPE_ID = 'USER_TYPE_ID';
	const XML_ID = 'XML_ID';
	const SETTINGS_DEFAULT_VALUE = 'DEFAULT_VALUE';
	const SETTINGS_MAX_LENGTH = 'MAX_LENGTH';
	const SETTINGS_MIN_LENGTH = 'MIN_LENGTH';
	const SETTINGS_REGEXP = 'REGEXP';
	const SETTINGS_ROWS = 'ROWS';
	const SETTINGS_SIZE = 'SIZE';
}