name: "Integration tests"

on:
  push:
    branches:
      - dev
  pull_request:

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"
  BITRIX24_PHP_SDK_PLAYGROUND_WEBHOOK: ${{ secrets.BITRIX24_PHP_SDK_PLAYGROUND_WEBHOOK }}

jobs:
  tests:
    name: "Integration tests"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
        dependencies: [ highest ]
        operating-system: [ ubuntu-latest, windows-latest ]

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: variables_order=EGPCS
        env:
          BITRIX24_PHP_SDK_PLAYGROUND_WEBHOOK: ${{ secrets.BITRIX24_PHP_SDK_PLAYGROUND_WEBHOOK }}

      - name: "Install dependencies"
        run: |
          composer update ${{ env.COMPOSER_FLAGS }}

      - name: "Debug ENV variables"
        run: |
          printenv

      - name: "Run integration tests"
        run: |
          composer phpunit-run-integration-tests

      - name: "integration tests succeeded"
        if: ${{ success() }}
        run: |
          echo '✅ integration tests pass, congratulations!'

      - name: "integration tests failed"
        if: ${{ failure() }}
        run: |
          echo '::error:: ❗integration tests failed (╯°益°)╯彡┻━┻ '